version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: mechanicdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mechanicdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      APP_SECURITY_JWT_SECRET: change-me-please-very-secret-and-long
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  db_data:
