spring:
  application:
    name: mechanic-on-demand
  
  datasource:
    url: jdbc:mysql://localhost:3306/mechanic_ondemand?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        
  security:
    jwt:
      secret: mySecretKey
      expiration: 86400000 # 24 hours

server:
  port: 8080

logging:
  level:
    com.mechanicondemand: DEBUG
    org.springframework.security: DEBUG